#!/usr/bin/env python3
# afm2c.py - character widths of the standard PostScript fonts for the
# print engine (src/html_print.c)
#
# Copyright (c) 2026 André Gewert <agewert@ubergeek.de>, MIT License
#
#   afm2c.py <directory with the Adobe Core AFM files> src/html_afm.c
#
# Reads helvetica.afm, helvetica-bold.afm, times-roman.afm, times-bold.afm,
# times-italic.afm and times-bolditalic.afm (Adobe Core 14 font metrics,
# free to use and distribute) and writes the widths of the ISO-8859-1
# characters 32..255 in 1/1000 em, plus the glyph names of the encoding
# used in the PostScript output. Oblique Helvetica has the widths of the
# upright one, Courier is 600 throughout.

import sys, os

NAMES = (
    # 32..126
    'space exclam quotedbl numbersign dollar percent ampersand quotesingle '
    'parenleft parenright asterisk plus comma hyphen period slash '
    'zero one two three four five six seven eight nine colon semicolon '
    'less equal greater question at '
    'A B C D E F G H I J K L M N O P Q R S T U V W X Y Z '
    'bracketleft backslash bracketright asciicircum underscore grave '
    'a b c d e f g h i j k l m n o p q r s t u v w x y z '
    'braceleft bar braceright asciitilde').split() + ['.notdef'] * 33 + (
    # 160..255
    'space exclamdown cent sterling currency yen brokenbar section dieresis '
    'copyright ordfeminine guillemotleft logicalnot hyphen registered macron '
    'degree plusminus twosuperior threesuperior acute mu paragraph '
    'periodcentered cedilla onesuperior ordmasculine guillemotright onequarter '
    'onehalf threequarters questiondown '
    'Agrave Aacute Acircumflex Atilde Adieresis Aring AE Ccedilla Egrave Eacute '
    'Ecircumflex Edieresis Igrave Iacute Icircumflex Idieresis Eth Ntilde Ograve '
    'Oacute Ocircumflex Otilde Odieresis multiply Oslash Ugrave Uacute '
    'Ucircumflex Udieresis Yacute Thorn germandbls '
    'agrave aacute acircumflex atilde adieresis aring ae ccedilla egrave eacute '
    'ecircumflex edieresis igrave iacute icircumflex idieresis eth ntilde ograve '
    'oacute ocircumflex otilde odieresis divide oslash ugrave uacute '
    'ucircumflex udieresis yacute thorn ydieresis').split()
assert len(NAMES) == 224, len(NAMES)

FONTS = [('helvetica', 'Helvetica'), ('helvetica-bold', 'Helvetica-Bold'),
         ('times-roman', 'Times-Roman'), ('times-bold', 'Times-Bold'),
         ('times-italic', 'Times-Italic'), ('times-bolditalic', 'Times-BoldItalic')]


def widths(path):
    w = {}
    for line in open(path, encoding='latin-1'):
        if line.startswith('C '):
            f = dict(p.strip().split(None, 1) for p in line.split(';') if p.strip() and ' ' in p.strip())
            w[f['N']] = int(f['WX'])
    return w


def main():
    src, out = sys.argv[1], sys.argv[2]
    lines = ['/* html_afm.c - generated by tools/afm2c.py from the Adobe Core 14 AFM files,',
             ' * do not edit. Widths of ISO-8859-1 characters 32..255 in 1/1000 em. */',
             '', '#include "html_print.h"', '',
             '/* glyph names of the encoding used in the PostScript output, 32..255 */',
             'const char *const hp_glyph_names[224] = {']
    for i in range(0, 224, 6):
        lines.append('    ' + ' '.join('"%s",' % n for n in NAMES[i:i + 6]))
    lines += ['};', '']
    for fn, ps in FONTS:
        w = widths(os.path.join(src, fn + '.afm'))
        cname = 'hp_w_' + fn.replace('-', '_')
        lines.append('/* %s */' % ps)
        lines.append('const unsigned short %s[224] = {' % cname)
        vals = [w.get(n, w['space']) if n != '.notdef' else 0 for n in NAMES]
        for i in range(0, 224, 14):
            lines.append('    ' + ', '.join('%4d' % v for v in vals[i:i + 14]) + ',')
        lines += ['};', '']
    open(out, 'w', encoding='latin-1', newline='\n').write('\n'.join(lines))


if __name__ == '__main__':
    main()
