/*
 * html_print.h - PostScript and PDF output of a document
 *
 * Lays the document out again with the metrics of the standard PostScript
 * fonts (Helvetica or Times, Courier) for the width of the paper, breaks
 * it into pages and writes PostScript (level 1 with optional level 2
 * page size) or PDF 1.4. Text stays text, no fonts are embedded; the
 * characters are ISO-8859-1. Platform independent like the rest of the
 * core: the output goes through a callback.
 *
 * Copyright (c) 2026 André Gewert <agewert@ubergeek.de>
 * Released under the MIT License, see LICENSE.
 */
#ifndef HTML_PRINT_H
#define HTML_PRINT_H

#include "html_core.h"

enum { HP_PS, HP_PDF };

/* results of html_print() besides the number of pages written */
#define HP_ERROR    (-1)            /* out of memory */
#define HP_ABORTED  (-2)            /* the progress callback asked to stop */

/* pixels of a picture, filled by the image callback */
struct HPrintImage {
    long                 w, h;      /* size in pixels */
    const unsigned long *argb;      /* w * h pixels 0xAARRGGBB, row by row; A = 255: opaque */
    void                *priv;      /* for the callback */
};

struct HPrintOpts {
    int         format;             /* HP_PS or HP_PDF */
    long        paper_w, paper_h;   /* paper size in points (A4: 595 x 842) */
    long        margin[4];          /* left, top, right, bottom in points */
    long        font_size;          /* normal text size in 1/10 points (100 = 10 pt) */
    int         serif;              /* proportional text in Times, else Helvetica */
    int         backgrounds;        /* print background colours */
    int         fit_images;         /* pictures not wider than the text (HEnv.fit_images) */
    const char *footer;             /* page numbers, "%p" page, "%n" pages; NULL: none */
    const char *title;              /* document title (PDF info, PS %%Title) or NULL */
    long        first, last;        /* pages to write, from 1; 0 = from the first / to the last */
    /* output: data of 'len' bytes */
    void      (*write)(void *user, const char *data, long len);
    /* called before each page; non-zero stops (HP_ABORTED) */
    int       (*progress)(void *user, long page, long pages);
    /* pixels of a picture (HNode.img); 0 if not available: a frame is
     * drawn instead. image_free() is called when they are written.    */
    int       (*image)(void *user, void *img, struct HPrintImage *pi);
    void      (*image_free)(void *user, struct HPrintImage *pi);
    void       *user;
};

/* Writes the document. Returns the number of pages written, HP_ERROR
 * or HP_ABORTED. *pages (optional) gets the number of pages of the
 * whole document.                                                     */
long html_print(struct HDoc *doc, const struct HPrintOpts *o, long *pages);

/* also for the bitmap printing of htmlttf.gadget: page tops of a layout
 * in its units for pages of 'height' (allocated from 'pool'), and the
 * footer text with %p and %n replaced                                 */
long *html_print_paginate(struct HLayout *lay, void *pool, long height, long *count);
long  html_print_footer(char *buf, long size, const char *fmt, long page, long pages);

/* character widths (html_afm.c, generated by tools/afm2c.py) */
extern const char *const hp_glyph_names[224];
extern const unsigned short hp_w_helvetica[224], hp_w_helvetica_bold[224];
extern const unsigned short hp_w_times_roman[224], hp_w_times_bold[224];
extern const unsigned short hp_w_times_italic[224], hp_w_times_bolditalic[224];

#endif /* HTML_PRINT_H */
